### PR TITLE
Ignore tags field to enable support for latest RIAAS API version 2020…

### PR DESCRIPTION
**Pull request by sameshai**
…-07-02

### CODE REVIEW

**Comment by sameshai** [comment]
Tested with PRs in IBMcloud-common and CSI driver there is no impact. We are good to remove tags from RIAAS payload.
We do see the tags attached in the "ibmcloud is" command and UI.

**Comment by arahamad** [comment]
Changes looks good, it would be good if you can test the mounting volume to pod and deleting pod i.e attach and detach flow so that we will be sure that this default version is good

**Comment by sameshai** [comment]
> Changes looks good, it would be good if you can test the mounting volume to pod and deleting pod i.e attach and detach flow so that we will be sure that this default version is good

I missed to mentioned in my previous comment that attach was tested updating below

2.) Deployed CSI driver with existing API version in unexpected time format i.e 2019-07-02T. This caused parsing error in CSI driver and we default to "2020-07-02"
a.) CSI Controller pods were up and running
b.) Create custom storage class with tags field
c.) Created PVC using #b custom storage class
d.) Create Deployment using #c PVC
e.) Verified via ibmcloud is command and UI that tags were persisted and attachement exist
f.) Verified via logs that tags was not forwarded to RIAAS APIs and update volume of microservice did updated the tags.
g.) Verified by logging on the node/pod that volumeattachment is working using lsblk and creating dir/files
e.) Verified by kubectl get volumeattachments    
e.) Verified by deleting the pod that detach is working and then confirmed with "volumeattachments"  and "is" command

**Review by arahamad — APPROVED** [review]
LGTM

**Review by akgunjal — APPROVED** [review]
LGTM

**Pull request merged**
